name: Auto Deploy on Push (Both VMs)

on:
  push:
    branches:
      - main

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    name: Deploy to Dev VM

    steps:
      - name: Deploy to Dev VM
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.DEV_VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.DEV_VM_SSH_KEY }}
          script: |
            cd ~/PNG-Provisioner
            
            echo "🚀 AUTO DEPLOYMENT - DEV"
            echo "Branch: ${{ github.ref_name }}"
            echo ""
            
            # Update repo
            git pull origin main
            
            # Copy dev docker-compose
            if [ -f dev/docker-compose.yml ]; then
              cp dev/docker-compose.yml docker-compose.yml
            fi
            
            # Login to GHCR
            echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            
            # Update ALL containers
            docker compose pull
            docker compose up -d --remove-orphans
            
            # Cleanup
            docker image prune -f
            
            # Status
            echo ""
            docker compose ps
            echo ""
            echo "✅ Dev deployment completed!"

  deploy-prod:
    runs-on: ubuntu-latest
    name: Deploy to Prod VM

    steps:
      - name: Deploy to Prod VM
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            cd ~/PNG-Provisioner
            
            echo "🚀 AUTO DEPLOYMENT - PROD"
            echo "Branch: ${{ github.ref_name }}"
            echo ""
            
            # Update repo
            git pull origin main
            
            # Copy prod docker-compose
            if [ -f prod/docker-compose.yml ]; then
              cp prod/docker-compose.yml docker-compose.yml
            fi
            
            # Login to GHCR
            echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            
            # Update ALL containers
            docker compose pull
            docker compose up -d --remove-orphans
            
            # Cleanup
            docker image prune -f
            
            # Status
            echo ""
            docker compose ps
            echo ""
            echo "✅ Prod deployment completed!"