name: Auto Deploy on Push (Both VMs)

on:
  push:
    branches:
      - main

jobs:
  trigger-deploys:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: write

    steps:
      - name: Dispatch repository events to trigger deploy workflows
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          script: |
            async function dispatch(env, version) {
              await github.rest.repos.createDispatchEvent({
                owner: context.repo.owner,
                repo: context.repo.repo,
                event_type: 'service_updated',
                client_payload: { service: 'all', version: version, environment: env }
              });
              console.log(`Dispatched repository_dispatch for ${env}`);
            }

            await dispatch('dev', 'dev');
            await dispatch('prod', 'latest');
